# Generated by Django 4.1.7 on 2023-06-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAdjective', models.CharField(max_length=50, unique=True)),
                ('nameSingular', models.CharField(max_length=50, unique=True)),
                ('namePlural', models.CharField(max_length=50, unique=True)),
                ('days', models.IntegerField(unique=True)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('requireDeposit', models.BooleanField(default=False)),
                ('frequency', models.ManyToManyField(to='merchant.frequencysettings')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('installmentConfiguration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchant.installmentconfiguration')),
            ],
        ),
    ]
