# Generated by Django 4.1.7 on 2023-06-16 16:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAdjective', models.CharField(max_length=50, unique=True)),
                ('nameSingular', models.CharField(max_length=50, unique=True)),
                ('namePlural', models.CharField(max_length=50, unique=True)),
                ('days', models.IntegerField(unique=True)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('requireDeposit', models.BooleanField(default=False)),
                ('minimumDepositPercentage', models.IntegerField(default=0)),
                ('minimumDepositAmount', models.IntegerField(default=0)),
            ],
        ),
    ]
